d-edge/foss-acronyms

README.md
=> Add VCS and SCM

README.md
Hey, I have added description for DRY in README.md, and specific resource link to get further idea behind it
=> DRY Acronym

README.md
First contrib here! :tada:
A slightly censored definition of RTFM.
GO D-Edge open source! :rocket:
=> Add RTFM definition

.github/workflows/markdown-from-json.yml, README.md, data/acronyms.json, data/organizations.json, data/stacks.json
Hello,
Let's split content from presentation. I wrote a blog post about the logic behind this PR: [
From JSON to MD with GHA](https://aloisdg.netlify.app/posts/from-json-to-md-with-gha/). Basically we are moving the content into JSON files and formatting into the `README.md` on pushed. You can see a demo of this PR at [json-to-md](https://github.com/aloisdg/json-to-md).
Cheers,
=> Split content from presentation

data/chat-acronyms.json
Contains mostly used chat acronyms
=> Add a new `chat-acronyms.json` file

data/acronyms.json
=> Adding WDYT

data/acronyms.json
=> Add AFAICT example

data/acronyms.json, data/chat-acronyms.json
=> Add AFAIK details, BRB , IRL , DTO , AFK

data/chat-acronyms.json
=> Add acronym for iykyk

data/acronyms.json
* DevOps stands for Development operations
=> Add DevOps (#67)

data/acronyms.json
=> Add PEBCAK

data/acronyms.json
=> Add DX to Acronyms

data/stacks.json
=> Update stacks.json with LAMP's examples

data/chat-acronyms.json
Added LOL aka "Laugh out loud" as an acronym.
=> Add LOL in chat acronyms

data/acronyms.json
=> Add DIP to acronyms

data/acronyms.json
=> Add SE, SWE, SRE

data/acronyms.json
=> Add Whisper's discussion as example for YMMV

data/acronyms.json
=> Add example to CoC

data/acronyms.json
=> Add RFP, RFI and RCE acronyms

data/acronyms.json, data/chat-acronyms.json
=> Add tyvm acronym and fixed syntax error

data/chat-acronyms.json
=> Add RTL/LTR (#43)

data/organizations.json
=> Added Amazon Web Services in organizations.json

data/acronyms.json
=> Add "DoD" acronyms

data/organizations.json
=> Add youtube acronym organization

data/acronyms.json
=> Add RTFA, TFA, DAG

data/acronyms.json
=> Add acronym AFK

data/acronyms.json
=> Add AD (Architectural Decision) 

data/acronyms.json
=> Add ADR, AKM, and ASR 

data/acronyms.json
=> added KPI to the list

data/acronyms.json
=> Added GATs into data/acronyms.json

data/acronyms.json
=> add KYC and KYB to acronym file

data/acronyms.json
=> #133 quick fix json syntax on RICE Example line
